Intermediate state: generates code that should work, but doesn't.
The reason it doesn't is that the EBPF not-quite-C language doesn't
support aggregate returns:

128bit_control_blocks.c:379:25: error: aggregate returns are not supported
  379 | struct internal_bit_127 add_127(struct internal_bit_127 lhs, struct internal_bit_127 rhs)
      |                         ^

Turns out it _semi_-supports them; if I manually edit the files so the
functions are not declared in the .h and present early in the .c as
"static __always_inline", then the resulting code compiles.